version: '{build}'
skip_tags: true
clone_depth: 2
environment:
  matrix:
  - appveyor_build_worker_image: Visual Studio 2022
    JAVA_HOME: C:\Program Files\Java\jdk17
branches:
  only:
  - master
os: Windows Server 2012
install:
- cmd: SET MAVEN_OPTS=-Xmx4g
- cmd: SET JAVA_OPTS=-Xmx4g
- cmd: mvn --version
- cmd: java -version
build_script:
- mvn clean package -B -Dmaven.test.skip=true
test_script:
- mvn clean install --batch-mode -Pqulice
cache:
- C:\Users\appveyor\.m2
artifacts:
- path: target/ExtraHardMode.jar
  name: ExtraHardMode
